#this is rewritten
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: <%= ENV['USERNAME'] %>
  password: <%= ENV['PASSWORD'] %>

development:
  <<: *default
  database: instapost_development

test:
  <<: *default
  database: instapost_test

production:
  <<: *default
  encoding: unicode
  database: instapost_production
